export const ADD_TO_CART = 'ADD_TO_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const TOGGLE_AMOUNT = 'TOGGLE_AMOUNT';
export const CALCULATE_AMOUNT_AND_ITEM = 'CALCULATE_AMOUNT_AND_ITEM';
